import { scryptSync, timingSafeEqual } from "node:crypto";
import { OAuthConfigError } from "./errors";

/**
 * The dedicated owner sign-in identity (data-model.md OwnerCredential,
 * spec.md FR-009) — separate from the S3/MinIO storage credentials in
 * lib/storage/config.ts. `passwordHash` is a `<salt>:<derivedKey>` scrypt
 * pair (research.md §4), produced by scripts/hash-owner-password.mjs.
 */
export interface OwnerCredentialConfig {
  username: string;
  passwordHash: string;
}

/**
 * Reads OAUTH_OWNER_USERNAME / OAUTH_OWNER_PASSWORD_HASH from process.env.
 * Never throws, even if missing — safe to call at module-import time
 * (mirrors lib/storage/config.ts's readStorageConfig()). Use
 * validateOwnerCredentialConfig() to check the result before relying on it.
 */
export function readOwnerCredentialConfig(): OwnerCredentialConfig {
  return {
    username: process.env.OAUTH_OWNER_USERNAME?.trim() ?? "",
    passwordHash: process.env.OAUTH_OWNER_PASSWORD_HASH?.trim() ?? "",
  };
}

const SCRYPT_HASH_PATTERN = /^[0-9a-f]+:[0-9a-f]+$/i;

/**
 * Validates a config produced by readOwnerCredentialConfig(), throwing
 * OAuthConfigError naming every missing field, or describing the malformed
 * one — called once at process startup (frontend/instrumentation.ts).
 */
export function validateOwnerCredentialConfig(config: OwnerCredentialConfig): void {
  const missing: string[] = [];
  if (!config.username) missing.push("OAUTH_OWNER_USERNAME");
  if (!config.passwordHash) missing.push("OAUTH_OWNER_PASSWORD_HASH");
  if (missing.length > 0) {
    throw new OAuthConfigError(`Missing required OAuth owner configuration: ${missing.join(", ")}`);
  }

  if (!SCRYPT_HASH_PATTERN.test(config.passwordHash)) {
    throw new OAuthConfigError(
      'OAUTH_OWNER_PASSWORD_HASH must be a "<salt>:<hash>" hex pair generated by ' +
        "`node scripts/hash-owner-password.mjs '<password>'`",
    );
  }
}

/** Reads and validates the owner credential config in one step (frontend/instrumentation.ts). */
export function verifyOwnerCredentialConfig(): void {
  validateOwnerCredentialConfig(readOwnerCredentialConfig());
}

/**
 * Verifies `password` against `passwordHash` (a `<salt>:<derivedKey>` scrypt
 * pair, research.md §4), using a timing-safe comparison.
 */
export function verifyOwnerPassword(password: string, passwordHash: string): boolean {
  const [saltHex, expectedHex] = passwordHash.split(":");
  if (!saltHex || !expectedHex) return false;

  const expected = Buffer.from(expectedHex, "hex");
  const actual = scryptSync(password, Buffer.from(saltHex, "hex"), expected.length);
  return expected.length === actual.length && timingSafeEqual(expected, actual);
}
